//	Copyright 2019 IBM Corporation and others.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
//
:page-layout: guide
:projectid: use-appsody-cli
:page-duration: 15 minutes
:page-releasedate: 2019-09-24
:page-description: Learn about the common Appsody CLI commands that you'll use to develop applications
:guide-author: Kabanero
:page-tags: ['appsody', 'CLI']
:page-guide-category: developer
:page-essential: true
:page-essential-order: 1
:page-permalink: /guides/use-appsody-cli/
:imagesdir: /resources
= Developing with the Appsody CLI

[.hidden]
NOTE: This repository contains the guide documentation source. To view
the guide in published form, view it on the https://kabanero.io/guides/ website.

Learn about the common Appsody CLI commands that you'll use to develop applications in the context of Kabanero and Kabanero CollectionHub.

// =================================================================================================
// What you'll learn
// =================================================================================================


== What you’ll learn

You will learn how to use the Appsody Command Line Interface (CLI) to  configure your local
development environment to access a Kabanero Collection. You will then learn how to use the CLI
to create, run, test, and deploy an application built from a Kabanero Collection.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisities

. link:https://docs.docker.com/install/[Docker] must be installed.
. link:https://appsody.dev/docs/getting-started/installation[Appsody] must be installed.

// =================================================================================================
// Discovering Appsody repositories and stacks
// =================================================================================================

== Discovering Appsody repositories and stacks

Appsody is an intergal component of Kabanero, its designed to enable applications to be built and tested inside a docker container, which then can be deployed by Kabanero into a target host environment.  

**CLI command:** `appsody repo list`

When you install Appsody, the default configuration references a public repository `appsodyhub`, in which you can see the available Appsody stacks. You can use the content in the public repository, but those stacks are not integrated with Kabanero. In order to use Appsody with Kabanero you need to add your Kabanero `collectionHub` to Appsody to be used. This
repository might be one that you create, based on your own requirements. Alternatively, the repository might be a
preconfigured Kabanero Collection that someone in your organisation, such as an enterprise architect, has created for you. In either case the collectionHub must be active in the Kabanero instance that you wish to deploy your application on,  and it must be added to Appsody for your application creation.

To see the list of configured Appsody repositories, run the `appsody repo list` command. The asterisk shown in the
output indicates the default repository.

[source,bash]
----
NAME            URL
*appsodyhub     https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
experimental    https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
----

=== Adding a Kabanero collection hub

**CLI command:** `appsody repo add <repo-name> <URL>`

As a developer your enterprise architect might provide you with the URL of a collection hub that your organisation
has defined for developers to use. A collection hub is defined by an `index.yaml` file, which lists all the collections
that are available.

To add a collection hub, use the `appsody repo add <repo-name> <URL>` command, supplying a name for the
repository and the URL for the collection hub. The URL must point to the collection hub's `index.yaml` file.

Run the following command to add the latest public Kabanero Collections repository (it is recommended that the installer of the Kabanero runtime, make a copy of the collection hub and provide that to you, so that you are not suprised when the public collection hub changes)

```
appsody repo add kabanero https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.yaml
```

Check that the repository changes are added successfully by running the `appsody repo list` command
again. The output should be similar to the following example:

[source,bash]
----
NAME          URL
*appsodyhub   https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
experimental  https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
kabanero      https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.yaml
----

=== Setting your default repository

**CLI command:** `appsody repo set-default <repo-name>`

You can change the default repository by using the `appsody repo set-default <repo-name>` command.

Set the `kabanero` collection hubb as your default repository by using the following command:

`appsody repo set-default kabanero`

Run `appsody repo list` again to check that `kabanero` is now the default repository:

[source,bash]
----
NAME            URL
*kabanero       https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.yaml
appsodyhub      https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
experimental    https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
----

The asterisk indicates that `kabanero` is now the default repository.

=== Viewing the available stacks

**CLI command:** `appsody list <repo-name>`

Now that you have set up your repositories you can view the available stacks with the `appsody list` command. To limit the
output to only one repository, specify the repository name. Run the following command to limit the list of available stacks
to the `kabanero` repository:

```
appsody list kabanero
```

The output is similar to the following example, which provides detailed information for each stack:

[source,bash]
----
REPO          ID                       VERSION    TEMPLATES           DESCRIPTION
kabanero      java-microprofile        0.2.11     *default            Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
kabanero      java-spring-boot2        0.3.9      *default, kotlin    Spring Boot using OpenJ9 and Maven
kabanero      nodejs                   0.2.5      *simple             Runtime for Node.js applications
kabanero      nodejs-express           0.2.5      *simple, skaffold   Express web framework for Node.js
kabanero      nodejs-loopback          0.1.4      *scaffold           LoopBack 4 API Framework for Node.js
----

In the output you can see multiple stacks (IDs) in the `kabanero` collection hub. Each collection includes a version number,
one or more templates (the asterisk (*****) indicates the default template), and a description.

// =================================================================================================
// Creating an Appsody application
// =================================================================================================


== Creating an Appsody/Kabanero application

**CLI command:** `appsody init <repo-name>/<stack> <template>`

An Appsody project gives you a containerized development environment that runs with the technology stack of your choice.

Before you create an Appsody project, create a directory to contain the application:

```
mkdir my-project
cd my-project
```

Then you can run the `appsody init` command to set up your project, which downloads the template for your
chosen stack. Because you already set `kabanero` as your default repository in the last section, run the following command
to create a Kabanero `nodejs-express` project with the default (`simple`) template:

```
appsody init nodejs-express
```

When the initialization completes you should see the following output:

[source,bash]
---
...
Successfully initialized Appsody project
---

// =================================================================================================
// Running an Appsody application
// =================================================================================================

== Running an Appsody application

**CLI command:** `appsody run`

This command runs an Appsody project in a docker container, where the container is linked to the project
source code on the local system. In the previous step, you initialized the `nodejs-express` collection, which created
a project directory that contains a sample `app.js` application. Run the application now by typing the `appsody run` command.

Navigate to `http://localhost:3000` to see the output.

**Note:** The URL can be different, depending on the collection, so consult the collection's documentation.

Now try editing `app.js` so that it outputs something other than "Hello from Appsody!". When you save the file,
Appsody picks up the change and automatically updates the container. Refresh `http://localhost:3000` to see the new message.


// =================================================================================================
// Checking the status of your Appsody container
// =================================================================================================

=== Checking the status of your Appsody container

**CLI command:** `appsody ps`

To list all the stack-based containers that are running in your local Docker environment, use the `appsody ps` command.
The output provides information about the container ID, name, image, and the status of each container.

Run the `appsody ps` command to see output that is similar to the following example:

[source,bash]
---
CONTAINER ID	NAME            IMAGE                     	STATUS
f20ec098a612	my-project-dev	appsody/nodejs-express:0.2	Up 8 minutes
---


// =================================================================================================
// Stopping your Appsody container
// =================================================================================================

=== Stopping your Appsody container

**CLI command:** `appsody stop --name <container-name>`

To stop a container you can either, press `Ctrl-C` in the terminal or use the `appsody stop` command, which
stops the container that is running in your current working directory.

If you have more than one development project open, use the `appsody stop --name <container-name>` to stop a specific container.
Use the `appsody ps` command to find the name of the container you want to stop.
