//	Copyright 2019 IBM Corporation and others.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
//
:page-layout: guide
:projectid: use-appsody-cli
:page-duration: 15 minutes
:page-releasedate: 2019-09-24
:page-description: Learn about the common Appsody CLI commands that you'll use to develop applications
:guide-author: Kabanero
:page-tags: ['appsody', 'CLI']
:page-guide-category: developer
:page-essential: true
:page-essential-order: 1
:page-permalink: /guides/use-appsody-cli/
:imagesdir: /resources
= Developing with the Appsody CLI

[.hidden]
NOTE: This repository contains the guide documentation source. To view
the guide in published form, view it on the https://kabanero.io/guides/ website.

Learn about the common Appsody CLI commands that you'll use to develop applications

// =================================================================================================
// What you'll learn
// =================================================================================================


== What you’ll learn

You will learn how to develop your own Appsody projects using the
Appsody Command Line Interface (CLI). This will include how to discover
the Appsody repositories that are available, how to add a new repository,
and how to display the stacks available within these repositories.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisities

. link:https://docs.docker.com/install/[Docker] must be installed.
. link:https://appsody.dev/docs/getting-started/installation[Appsody] must be installed.

// =================================================================================================
// Discover the Appsody repositories and stacks
// =================================================================================================

== Discover the Appsody repositories and stacks

When you install Appsody it contains a reference to a public repository `appsodyhub`, in which you can see the available
Appsody stacks. You can use the content in the public repository, or you can specify a different repository. This
repository might be one that you create, based on your own requirements. Alternatively, the repository might be a
preconfigured Kabanero Collection that someone in your organisation, such as an enterprise architect, has created for you.

To see the list of configured Appsody repositories, run the `appsody repo list` command. The asterisk shown in the
output indicates the default repository.

[source,bash]
----
NAME            URL
*appsodyhub     https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
experimental    https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
----

=== Adding your own Appsody repository

As a developer your enterprise architect might provide you with the URL of a repository that your organisation
has defined for developers to use. A repository is defined by an `index.yaml` file, which lists all the stacks
that are available.

To add this repository, use the `appsody repo add <repo-name> <URL>` command, supplying a name for the
repository and the URL for the repository. The URL must point to the `index.yaml` file for your repository.
The following example adds the latest public Kabanero Collections repository:

```
appsody repo add kabanero https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.yaml
```

When you've added your repository, check that it's been added successfully by running the `appsody repo list` command
again. The output should be similar to the following sample:

[source,bash]
----
NAME          URL
*appsodyhub   https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
experimental  https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
kabanero      https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.yaml
----

You can change the default repository by using the `appsody repo set-default <name>` command.

For example, to set the `kabanero` repository as your default repository, use the following command:

`appsody repo set-default kabanero`

Run `appsody repo list` again to see that `kabanero` is now the default repository:

[source,bash]
----
NAME            URL
*kabanero       https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.yaml
appsodyhub      https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
experimental    https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
----

=== Viewing the available stacks

Now that you have set up your repositories you can view the available stacks with the `appsody list` command. To limit the
output to only one repository, specify the repository name. For example, to limit the list of available stacks to the
`kabanero` repository, run:

```
appsody list kabanero
```

The output is similar to the following sample, which provides detailed information for each stack:

[source,bash]
----
REPO          ID                       VERSION    TEMPLATES           DESCRIPTION
kabanero      java-microprofile        0.2.11     *default            Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
kabanero      java-spring-boot2        0.3.9      *default, kotlin    Spring Boot using OpenJ9 and Maven
kabanero      nodejs                   0.2.5      *simple             Runtime for Node.js applications
kabanero      nodejs-express           0.2.5      *simple, skaffold   Express web framework for Node.js
kabanero      nodejs-loopback          0.1.4      *scaffold           LoopBack 4 API Framework for Node.js
----
